name: 'OCB 7D2D shared github action'
author: 'Marcel Greter'
description: 'Compile 7D2D modules (and releases)'

inputs:
  name:
    required: true
    type: string
  token:
    required: true
  OCBTOKEN:
    required: true
  release:
    required: false
    default: 'false'
    type: boolean
  version:
    required: false
    default: 'snapshot'
    type: string
  v7d2d:
    required: false
    default: 'A21.2'
    type: string
  prerelease:
    required: false
    default: 'false'
    type: boolean
  draft:
    required: false
    default: 'true'
    type: boolean

runs:
  using: composite
  steps:
  - name: Add msbuild to PATH
    uses: microsoft/setup-msbuild@v1.1
  - name: Update PowerShell Archive Version
    shell: powershell
    run: Install-Module Microsoft.PowerShell.Archive -MinimumVersion 1.2.3.0 -Repository PSGallery -Force
  - name: Checkout OCB7D2D compile helpers
    uses: actions/checkout@v3
    with:
      path: 'OCB7D2DCM'
      repository: OCB7D2D/OcbModCompiler
      ref: master
  - name: Checkout 7D2D A20 dependencies (private repo)
    uses: actions/checkout@v3
    with:
      repository: OCB7D2D/OCB7D2DCI
      token: ${{ inputs.OCBTOKEN }}
      path: 7D2DCI
  - name: Call OCB7D2D module compiler
    shell: cmd
    run: |
      set ROSLYN_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn
      set PATH_7D2D_MANAGED=7D2DCI/${{ inputs.v7d2d }}
      set PATH=%PATH%;OCB7D2DCM/utils
      00-CompileModule.bat
  - name: Create release archive
    shell: cmd
    run:
      01-CreateRelease.bat ${{ inputs.version }}
  - name: Create github release
    if: ${{ inputs.release == 'true' }}
    uses: "marvinpinto/action-automatic-releases@v1.2.1"
    with:
      repo_token: ${{ inputs.token }}
      prerelease: ${{ inputs.prerelease }}
      draft: ${{ inputs.draft }}
      files: |
        ./build/*.zip
    id: "automatic_releases"
