name: 'OCB 7D2D shared github action'
author: 'Marcel Greter'
description: 'Compile 7D2D modules (and releases)'

inputs:
  name:
    required: true
    type: string
  token:
    required: true
  OCBTOKEN:
    required: true
  release:
    required: false
    default: false
    type: boolean
  version:
    required: false
    default: 'snapshot'
    type: string

runs:
  using: composite
  steps:
  - name: Packaging release
    shell: cmd
    run: |
      01-CreateRelease.bat ${{ inputs.version }}
      xcopy build\*.zip .
      dir
  - name: Create release on tag 32
    if: ${{ inputs.release == 'true' }}
    uses: "marvinpinto/action-automatic-releases@v1.2.1"
    with:
      repo_token: ${{ inputs.token }}
      prerelease: false
      draft: true
      files: |
        "*.zip"
    id: "automatic_releases"
